version: "3.1"

services:
  nehuen_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: nehuen_db
      MYSQL_ROOT_USER: unehuen
      MYSQL_USER: unehuen
      MYSQL_ROOT_PASSWORD: nehuen
      MYSQL_PASSWORD: nehuen